config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :kill
  get "tasks/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @result = ''
    if @task.completed == false
      @result = "This task has not been completed"
    else
      @result = "This task has been completed"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>EDIT TASK</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit :update %>
<% end %>

app/views/tasks/index.html.erb
<div class="container text-center justify-content-center">
<h1>MY TASKS</h1>
<div class="d-flex">
  <ul class="list-unstyled mx-auto justify-content-center">
  <% @tasks.each do |task| %>
    <li class="">
      <div class=" container d-flex m-3 justify-content-between">
          <div>
            <input type="checkbox"  <% if task.completed %> checked <% end %> >
          </div>

          <div>
            <%= link_to task_path(task) do %>
            <p><%= "#{task.title}" %></p>
            <% end %>
          </div>

          <div>
            <%= link_to kill_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-thin fa-trash-can fa-lg" style="color: #da0b0b;"></i>
            <% end %>
          </div>
      </div>
    </li>
  <% end %>
  </ul>

</div>
<div class="bg-success">
<%= link_to "Add a new task", tasks_new_path %>
</div>
</div>

app/views/tasks/new.html.erb
<h1>NEW TASK</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<input type="checkbox"  <% if @task.completed %> checked <% end %> >
<p><%= "#{@result}" %></p>
<%= link_to "back to all the tasks", "/tasks"  %>

<%= link_to "edit this task",  edit_task_path(@task) %>